version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: planeja-pdf-ai-backend
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-planeja-pdf-ai-backend}
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Asdlkj3547!}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-root} -d ${POSTGRES_DB:-planeja-pdf-ai-backend}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: