"""Tabela conversations

Revision ID: 7ae593497572
Revises: 
Create Date: 2025-05-02 23:58:49.334073

"""
from typing import Sequence, Union

from alembic import op
from datetime import datetime
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae593497572'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'conversations',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('user_id', sa.String(), index=True),
        sa.Column('prompt', sa.String(), nullable=True),
        sa.Column('response', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), default=datetime.utcnow, nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
