name: Keep Supabase Alive

on:
  schedule:
    - cron: '0 0 * * *'  # Executa a cada 24 horas
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Install PostgreSQL client
        run: sudo apt-get install postgresql-client -y

      - name: Run dummy query on Supabase
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          psql "$SUPABASE_DB_URL" -c "SELECT NOW();"
          